### PR TITLE
font family and color updated.

### PR DESCRIPTION
**Pull request by RoopakMallik**
I have updated the issue regarding font family and color.
#73 updated

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add issue number

**Comment by RoopakMallik** [comment]
I have updated the issue regarding font family and color.
Issue #73 updated.

**Comment by samipak458** [comment]
@RoopakMallik kindly define issue

**Comment by RoopakMallik** [comment]
Issue #73  was related to addition of Font Family and make the background better.
This issue has been fixed and updated by making changes in the Html and CSS sections by my side.

**Comment by RoopakMallik** [comment]
@samipak458 
Issue #73  was related to addition of Font Family and make the background better.
This issue has been fixed and updated by making changes in the Html and CSS sections from my side.

**Pull request merged**
