### PR TITLE
Added read status and read status checkbox

### LINKED ISSUE #23: Adding read status in the library
Another option can be added in the display telling us whether we have read that book @samipak458

### PR DESCRIPTION
**Pull request by nalin243**
Closes #23

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly resolve the conflict @nalin243

**Comment by nalin243** [comment]
Done @samipak458

**Comment by samipak458** [comment]
Can you add screenshots ?

**Comment by nalin243** [comment]
readstatus

@samipak458

**Comment by samipak458** [comment]
It showing conflict on index.html, kindly resolve it.

**Comment by nalin243** [comment]
Done @samipak458

**Comment by samipak458** [comment]
Good job @nalin243 👍

**Pull request merged**
