### PR TITLE
Added a user login page

### PR DESCRIPTION
**Pull request by adwaith-krishna**
Added a simple user login page where user can login using his username and password.The login page hasn't been linked to the index.html file yet and the authentication stuff hasn't been done.

login

### CODE REVIEW

**Comment by samipak458** [comment]
Do you add sign up button in navbar?

**Comment by adwaith-krishna** [comment]
No,was planning to add a separate page with options for admin and user login then proceed to the main page.

**Comment by samipak458** [comment]
Yes, please add a separate page that say first login to manage the library and also add guest mode in which user can manage without login it.

**Comment by adwaith-krishna** [comment]
Yeah sure.Can you please merge the current pull request if you like it?

**Comment by samipak458** [comment]
Sure @ROCKSTAR040

**Pull request merged**
