### PR TITLE
Update azure-static-web-apps-delightful-coast-00b51a700.yml

### PR DESCRIPTION
**Pull request by sakshimishra19**

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add short video of your changes @sakshimishra19

**Comment by sakshimishra19** [comment]
I was facing this problem in my previous pull request,

 to fix it, I followed the direction and raised the second pull request. Maybe after this change the earlier problem will be solved .

**Comment by samipak458** [comment]
@sakshimishra19 do one thing delete your current fork and your PR. I think there is an issue with fork.

**Comment by sakshimishra19** [comment]
ok

**Pull request closed without merging**
