### PR TITLE
Added filter feature

### PR DESCRIPTION
**Pull request by RichardHanitio**
Hi, these are the changes I've made.

Here's how it looks :
image
image

Here's how it works :
1. All
image

2. Book Name
image

3. Book Author
image

4. Book Type
image

Please kindly let me know if there is any more changes that I need to make, thanks! 😊
One question though, does the "No. of books" depends on the search result? Or is it just displaying the overall number of books on our list?

### CODE REVIEW

**Comment by samipak458** [comment]
Hi @RichardHanitio,

Nice work. Yes, it's just displaying overall number of books. If no book available then it will show. I will merge PR after 1st October to that it will count in Hacktoberfest.

**Comment by samipak458** [comment]
In the mean time, can you improve the drop-down styling?

**Comment by RichardHanitio** [comment]
> In the mean time, can you improve the drop-down styling?

Ok I'm on it, thanks

**Comment by samipak458** [comment]
Hi,
Kindly sync the fork.

**Comment by RichardHanitio** [comment]
Hi, I have synced the fork. @samipak458 

As for the drop-down styling, here's how it looks now :
image

Honestly, I'm not satisfied with my drop-down options styling, but I can't find a way to change that, and bootstrap's official documentation stated that we cannot modify the options due to browser limitations.

**Comment by samipak458** [comment]
Great work @RichardHanitio. No issues it look good.

**Comment by Shashwat0227** [comment]
can you go through my pull request it was done before still it is not reviewed once

**Pull request merged**
