### PR TITLE
made website responsive

### PR DESCRIPTION
**Pull request by sarthakastic**
I have made the site responsive. Pls check it and let me know of any changes.

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly attached the screenshots or make video of changes

**Comment by sarthakastic** [comment]
The table was overflowing so I made it scrollable because there are too many columns.
Screenshot 2022-10-05 at 4 47 05 PM
Screenshot 2022-10-05 at 4 47 10 PM
Screenshot 2022-10-05 at 4 47 25 PM

**Comment by samipak458** [comment]
Do you reduce the columns in book shelf? 
Kindly add the remaining columns if you removed it.

**Comment by sarthakastic** [comment]
Yeah they were empty....ok i will add it.

**Comment by sarthakastic** [comment]
I have added the two columns

**Comment by samipak458** [comment]
Kindly resolve the conflicts

**Comment by samipak458** [comment]
Also add issue number to PR

**Comment by sarthakastic** [comment]
sure

**Comment by samipak458** [comment]
Kindly resolve conflicts.

**Comment by samipak458** [comment]
@sarthakastic still there is responsiveness issue. Kindly fix it.

**Comment by sarthakastic** [comment]
can u pls attach screenshot regarding the issue

**Comment by samipak458** [comment]
This is current website.

https://delightful-coast-00b51a700.1.azurestaticapps.net/

I'm unable to see the changes you made visually, I review your code. Kindly attach short video in which you can show the responsiveness of website.

**Pull request closed without merging**
