### PR TITLE
Added a guest login feature along with the user login

### PR DESCRIPTION
**Pull request by adwaith-krishna**
Added a feature where the user can login as guest in the user login page.

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add screenshots of your changes

**Comment by adwaith-krishna** [comment]
gu

**Comment by samipak458** [comment]
When website opens, this will be the first page?

**Comment by adwaith-krishna** [comment]
Yes

**Comment by adwaith-krishna** [comment]
If you want a separate page with signup option can also be added

**Comment by samipak458** [comment]
Sure, go ahead. Which database use used?

**Comment by samipak458** [comment]
Sure, go ahead. Which database you used?

**Comment by adwaith-krishna** [comment]
I haven't done the part where it does the authentication and stuff

**Comment by samipak458** [comment]
You make it static, right?

**Comment by adwaith-krishna** [comment]
Yes

**Comment by samipak458** [comment]
Kindly sync the fork @ROCKSTAR040

**Comment by samipak458** [comment]
Kindly sync the fork @ROCKSTAR040

**Comment by adwaith-krishna** [comment]
Done

**Pull request merged**
