### PR TITLE
Fix #16: duplicate addition of books

### LINKED ISSUE #16: Preventing same books from being added multiple times
Right now, books with same name, author and type can be added multiple times. Which increases redundancy!
I can work on this issue.

### PR DESCRIPTION
**Pull request by sumitbishti**
Closes #16

### CODE REVIEW

**Comment by sumitbishti** [comment]
@samipak458 Before merging the PR could you please add Hacktoberfest label onto it?

**Comment by samipak458** [comment]
Good job @sumitbishti  👍
Kindly resolve the conflicts.
Thank you

**Comment by sumitbishti** [comment]
@samipak458 It's done.

**Comment by samipak458** [comment]
Good job @sumitbishti 👍

**Comment by sumitbishti** [comment]
@samipak458 May i know why did you marked it as invalid?

**Pull request merged**
