### PR TITLE
done hovering and updated 

### PR DESCRIPTION
**Pull request by Shashwat0227**

### CODE REVIEW

**Comment by Shashwat0227** [comment]
now you can check sir , its done all issues are resolved

**Comment by Shashwat0227** [comment]
closes #10

**Comment by Shashwat0227** [comment]
before
search bar and searching before 
hoveronbutton
search nav bar
after..

after(clear)
clear shelf after
after(clear)
clear shelf before
before(clear)

**Comment by samipak458** [comment]
Good job @Shashwat0227

**Comment by Shashwat0227** [comment]
thankyou sir 
btw should i do that darkmode feature?

**Comment by Shashwat0227** [comment]
why removed it ?

**Comment by Shashwat0227** [comment]
on the source code itself my code is running then how come its invalid ? its merged also

**Pull request merged**
