### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sakshimishra19**
Removed checkbox ,moon and sun icon from header section ,changed Select filter into Filter 

Also removed checkbox and heart icon from Author section

### CODE REVIEW

**Comment by samipak458** [comment]
@sakshimishra19 kindly sync the fork

**Comment by samipak458** [comment]
To resolve the conflict

**Comment by sakshimishra19** [comment]
Done

**Comment by samipak458** [comment]
Good job @sakshimishra19

**Comment by samipak458** [comment]
@sakshimishra19 changes you made are not visible. Kindly check website and try to fix it. And also not mobile responsive.

**Pull request merged**
