### PR TITLE
FAQ Dark Mode - Fixes

### PR DESCRIPTION
**Pull request by muhammadhamzaanees**
If dark mode enabled then read the paragraph of faqs...

### CODE REVIEW

**Comment by muhammadhamzaanees** [comment]
FAQ Fixed

**Comment by samipak458** [comment]
Hi @mhamza2557,
Thanks for creating an PR. Kindly also Change the color of heading of FAQs to white.

**Comment by samipak458** [comment]
Someone has fixed this issue, kindly check.

**Pull request closed without merging**
