### PR TITLE
Made website Responsive

### PR DESCRIPTION
**Pull request by sarthakastic**

### CODE REVIEW

**Comment by sarthakastic** [comment]
I have gone through each conflict. It won't break the code it's done just to make it responsive and easy to read. The table conflict is solved by adding the column.

**Comment by samipak458** [comment]
Its still showing conflict in index.html. @sarthakastic do one thing add CSS in different file.

**Comment by samipak458** [comment]
@sarthakastic also add issue number which you fixed.

**Comment by sarthakastic** [comment]
Issue numbers #53 and #80 were solved.

**Comment by sarthakastic** [comment]
I have added css in another file.

**Comment by samipak458** [comment]
**Sync the fork because it showing conflicts.** @sarthakastic

**Pull request merged**
