### PR TITLE
Create a custom type of book

### LINKED ISSUE #19: Creating another type of book
I just made a very few changes to add a new type of book in my fork
29-09-2022-23h12min45

It also has a click management to toggle the input tag for all radio buttons and it will keep the type "Other" if you don't write anything inside the input. If this is an interesting feature, I'll be glad to make a PR.

### PR DESCRIPTION
**Pull request by diego-rapoport**
A simple input to manually create new types of books.

29-09-2022-23h12min45

Closes #19

### CODE REVIEW

**Comment by samipak458** [comment]
Hi,
Kindly sync the fork.

**Comment by samipak458** [comment]
Good job @diego-rapoport 👍
Kindly resolve the conflicts. 
Thank you

**Comment by samipak458** [comment]
Good job @diego-rapoport 👍

**Comment by diego-rapoport** [comment]
Thank you very much! I'm so glad to contribute.

**Pull request merged**
