### PR TITLE
done the hover of buttons and some transitions

### PR DESCRIPTION
**Pull request by Shashwat0227**
after(clear)
modified hover with a transition
before(clear)
the button without hover 

before

the search bar before the hover and the search button before the hover 
hoveronbutton

search nav bar
 the search bar and button after the hover

### CODE REVIEW

**Comment by Shashwat0227** [comment]
did synced the work and did again the work ,thanks for informing about syncing the fork , so can you merge the change now

**Comment by Shashwat0227** [comment]
can you please check it , and accept it ?

**Comment by samipak458** [comment]
Good job @Shashwat0227  👍
Kindly resolve the conflicts.
Thank you

**Comment by Shashwat0227** [comment]
someone who fixed the add button , removed my code from there itself , so i am adding that again

**Pull request closed without merging**
