### PR TITLE
Resolved the footer issue 

### PR DESCRIPTION
**Pull request by Ishikasaraf20**
hey @samipak458 i've made the footer kindly reveiw the changes and if you find this helpful kindly merge it your main branch

### CODE REVIEW

**Comment by Ishikasaraf20** [comment]
hey @samipak458 here's the PR kindly reveiw the changes

**Comment by samipak458** [comment]
@Ishikasaraf20 it is closed

**Comment by Ishikasaraf20** [comment]
sorry @samipak458 please now check thee PR

**Comment by samipak458** [comment]
Is it mobile responsive @Ishikasaraf20 ?

**Comment by Ishikasaraf20** [comment]
yes it iss

**Pull request merged**
