### PR TITLE
Mainbranch

### PR DESCRIPTION
**Pull request by vaibhavyadav-dev**
Changed the some display , added some icons and positioned some element in the project.
Hope you like it.

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add screenshots of your changes @CaptainTron

**Comment by vaibhavyadav-dev** [comment]
> Kindly add screenshots of your changes @CaptainTron 
Screenshot (58)
Screenshot (59)

**Comment by vaibhavyadav-dev** [comment]
Screenshot (60)

**Comment by samipak458** [comment]
Kindly change the colours of headings in Dark mode @CaptainTron

**Comment by samipak458** [comment]
Kindly sync the fork @CaptainTron 
I review your changes everything is fine just need to sync the fork.

**Comment by vaibhavyadav-dev** [comment]
> Kindly sync the fork @CaptainTron I review your changes everything is fine just need to sync the fork.

Done !!

**Pull request merged**
