### PR TITLE
Dropdown modified in index.html

### PR DESCRIPTION
**Pull request by dvig14**
Screenshot (14)
Screenshot (15)

### CODE REVIEW

**Comment by samipak458** [comment]
@dvig14 do you create an issue before?

**Comment by dvig14** [comment]
No ..

**Comment by samipak458** [comment]
Good job @dvig14

**Comment by samipak458** [comment]
@dvig14 kindly see the website the changes you made is not working, kindly fix it.

**Comment by samipak458** [comment]
Kindly fix it @dvig14 
So I will make it valid contribution
Website link: https://delightful-coast-00b51a700.1.azurestaticapps.net/

**Comment by dvig14** [comment]
Ok, I will c

**Comment by dvig14** [comment]
It's because my css code is not their in your style.css file which is
recently made ..
Otherwise it is working before.

**Pull request merged**
