### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by YashBawa**
Dark Mode added to the website 
Header color made a little brighter
It is in proper working condition . SS for reference.
Light Mode:-
image
Dark mode:-
image

### CODE REVIEW

**Comment by samipak458** [comment]
Good job 👍 @YashBawa

**Comment by samipak458** [comment]
Where is toggle button to switch mode?

**Comment by YashBawa** [comment]
Thank you 
The moon is visible in both light and dark modes, i added the official website ss by mistake 
here are the new ones:-
light mode
image
dark 
image

**Comment by samipak458** [comment]
Kindly add sun icon on light mode @YashBawa

**Pull request merged**
