### PR TITLE
fixed dark mode bugs

### LINKED ISSUE #54: bug: dark mode button toggle issue and improve dark mode design
Issues I encountered : 
- The dark mode button icon is not toggling well. 
- The nav bar is not so attractive, the search bar could be a bit longer
- In dark mode, date icon isn't visible
- There is no validation for ISBN number input field
- improve fonts and colors

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
resolve #54 

The table data is not visible in dark mode. fixed it in this pr.

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly resolve conflicts.

**Comment by samipak458** [comment]
Good job

**Comment by samipak458** [comment]
Dark mode not working, its just changing text field bg to black. Kindly have a look and fix it @saimaheshtaduri by creating new PR.

**Comment by saimaheshtaduri** [comment]
@samipak458 got it.

**Pull request merged**
