### PR TITLE
ADDED FOOTERS 

### PR DESCRIPTION
**Pull request by Shashwat0227**
added footers + copyright

### CODE REVIEW

**Comment by Shashwat0227** [comment]
Issue #12 solved

**Comment by samipak458** [comment]
@Shashwat0227 @DHCJS is working on this issue. @DHCJS have you added it or not?

**Comment by Shashwat0227** [comment]
Hey , check the issues , I was assigned first what is this ?first my headers hover is used in your main code and you setted it to invalid and now this issue , this is not right I have worked for this

**Comment by Shashwat0227** [comment]
Check once !

**Comment by ghost** [comment]
You can check my latest post on the issue @samipak458. @Shashwat0227, no hard feelings. I'll go with what the maintainer needs

**Comment by Shashwat0227** [comment]
> 

@DHCJS bro check one of the oldest issues , so it was assigned to me and i did all the work , and thats not even fair cuz it takes time ,
and maintainer so check it once ,

**Comment by samipak458** [comment]
@Shashwat0227 let @DHCJS do the enhancement then I will according to your work.

**Pull request closed without merging**
