### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sakshimishra19**

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add screenshots in desktop and mobile mode

**Comment by sakshimishra19** [comment]
Desktop view

Removed checkbox, moon and sun icon from Header section. Also removed heart icon and  checkbox from Author section
Mobile view

**Comment by samipak458** [comment]
Favorite section is missing, there is a toggle button in Favourite.

**Comment by samipak458** [comment]
Do one thing delete the fork and then try again.

**Comment by sakshimishra19** [comment]
ok

**Pull request closed without merging**
