### PR TITLE
add book button is fixed and working now

### LINKED ISSUE #61: fix add book button

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
resolves #61 

now the add book button is working fine

Screenshot (30)

### CODE REVIEW

**Comment by saimaheshtaduri** [comment]
@samipak458  please review it.

**Comment by samipak458** [comment]
Kindly add issue number and share screenshot of changes.

**Comment by saimaheshtaduri** [comment]
Actually, I didnt raise any issue. can I do it now ? @samipak458

**Comment by samipak458** [comment]
Yes, you can.

**Comment by saimaheshtaduri** [comment]
@samipak458  please review it now, and kindly add corresponding labels. Thanks

**Comment by samipak458** [comment]
Good job @saimaheshtaduri 👍

**Pull request merged**
