### PR TITLE
isbn no,publication date added

### PR DESCRIPTION
**Pull request by nileshlad09**

### CODE REVIEW

**Comment by samipak458** [comment]
@nileshlad09  Kindly resolve the conflicts.

**Comment by nileshlad09** [comment]
image

hi how can I resolve this conflicts I try to commit once again

**Comment by nileshlad09** [comment]
@samipak458 can you plz help me

**Comment by nileshlad09** [comment]
@samipak458  done you can check now

**Comment by samipak458** [comment]
Great work Nilesh 👍

**Pull request merged**
