### PR TITLE
added book url support

### LINKED ISSUE #48: add book urls and also the status of that book
I think it will be good, if ppl are able to store the url of the book. Thus on clicking the book, they will be able to read it online then and there it self. The status of the book ( if possible the page no where they stopped reading ) will also be useful.

### PR DESCRIPTION
**Pull request by saimaheshtaduri**
Now book url can also be added and on clicking the book title int he table, it redirects to the book link.

fix #48

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add issue number.

**Comment by saimaheshtaduri** [comment]
@samipak458  review it now

**Comment by saimaheshtaduri** [comment]
@samipak458

**Comment by samipak458** [comment]
Kindly resolve conflicts.

**Comment by saimaheshtaduri** [comment]
@samipak458 conflicts resolved

**Comment by samipak458** [comment]
Can you please add Screen shots

**Comment by saimaheshtaduri** [comment]
https://user-images.githubusercontent.com/53844369/194637052-59d31dd7-9c61-4829-a49a-11d43183bdff.mp4

@samipak458 done

**Comment by samipak458** [comment]
That's great but it's redirecting to Google is it possible if it redirects it open that book info in Google?

**Comment by saimaheshtaduri** [comment]
It redirects to the url given in the form. I gave  www.google.com as example. So it's redirecting there.

**Comment by samipak458** [comment]
Good job @saimaheshtaduri

**Pull request merged**
