### PR TITLE
Updatebranch

### PR DESCRIPTION
**Pull request by vaibhavyadav-dev**
Updated the color of heading in dark mode

### CODE REVIEW

**Comment by vaibhavyadav-dev** [comment]
> Updated the color of heading in dark mode

@samipak458 done

**Comment by samipak458** [comment]
Kindly add screenshots

**Comment by vaibhavyadav-dev** [comment]
> Kindly add screenshots

Screenshot (62)
Screenshot (63)

**Comment by vaibhavyadav-dev** [comment]
> > Kindly add screenshots
> 
> Screenshot (62) Screenshot (63)

@samipak458

**Pull request merged**
