### PR TITLE
Fixed Dark Mode and dark mode toggle button

### PR DESCRIPTION
**Pull request by KishorBhagat**
Fixed Dark Mode toggling Issue. Thanks :)

### CODE REVIEW

**Comment by samipak458** [comment]
Kindly add screenshots and also a short video of the changes

**Comment by KishorBhagat** [comment]
Light Mode
Dark Mode

**Comment by KishorBhagat** [comment]
Light Mode

**Comment by samipak458** [comment]
Good job @KishorBhagat 👍
Is it mobile responsive as well?

**Comment by KishorBhagat** [comment]
> 

It's working fine in mobile. But the design and alignment needed to be  improved!

**Comment by samipak458** [comment]
@KishorBhagat Can you improved it ? By making another PR.

I'm merging this PR.

**Comment by KishorBhagat** [comment]
> @KishorBhagat Can you improved it ? By making another PR.
> 
> I'm merging this PR.

I can give it a try!

**Pull request merged**
