### PR TITLE
Refactor functions

### PR DESCRIPTION
**Pull request by varshil-shah**
In this pull request, I've converted the updateBooks and showNumberOfBooks functions into ES6 functions.

### CODE REVIEW

**Comment by samipak458** [comment]
Good job @Varshil-Shah 👍 
Kindly resolve the conflicts.
Thank you

**Comment by samipak458** [comment]
@Varshil-Shah still showing conflict in script.js
For that reason I'm unable to merge it because merge button is disabled.

**Comment by varshil-shah** [comment]
Fixed 👍

**Comment by samipak458** [comment]
image

@Varshil-Shah kindly fix the error. If you're unable to do it then it will not count as a valid contribution.

**Comment by varshil-shah** [comment]
I'll fix it by tomorrow

**Pull request merged**
